version: '3'

services:
    nginx-cafe:
        container_name: nginx-link
        image: nginx:1.24.0
        restart: "no"
        ports:
            - "89:80"
        volumes:
            - .:/var/www/
            - ./.docker/config/nginx/:/etc/nginx/conf.d/
            - ./.docker/logs/nginx:/var/log/nginx/

    php-link:
        build:
            context: ./.docker/
        container_name: php-link
        restart: "no"
        tty: true
        working_dir: /var/www
        volumes:
            - .:/var/www/
